### ISSUE TITLE
Call super.start(promise) or super.start() in VaadinVerticle

### ISSUE THREAD

**Issue by Dudeplayz** [mcollovati/vertx-vaadin#45]
The `AbstractVerticle` calls in its default implementation a simple `start()` function. The `VaadinVerticle` implementation should call the `start` function or propagate to the super implementation. 
I am currently not using this function actively but I discovered this behavior while some testing.
 https://github.com/mcollovati/vertx-vaadin/blob/b0f4f952c118c4bbe77cf2e0a46e80297e1fbeed/vertx-vaadin-flow-parent/vertx-vaadin-flow/src/main/java/com/github/mcollovati/vertx/vaadin/VaadinVerticle.java#L95-L107

**Comment by mcollovati** [comment]
Not sure about that: since `AbstractVerticle` implementation of `start` is empty why should we call it?
If we need to customize the startup process we can override `start(Promise<Void> startFuture)` or the `serviceInitialized` hook.

Can you elaborate on the benefits of calling `super.start()`? Or on the troubles by not invoking it
Perhaps there's something I'm missing.

**Comment by mcollovati** [comment]
After discussion with @Dudeplayz we agreed on following behaviour: `start()` may be used for synchronous tasks to be performed at startup so `start(Promise<Void> promise)` should invoke it, but as last step, after `prepareConfig` starts the async operatons flow.

Same thing should be done for `stop(Promise<Void> promise)`, with the difference that `stop()` will be invoked before stopping httpServer, in order to let shutdown task complete before disposing the Verticle.
